import type { Metadata } from "next";
import "./globals.css";
import { montserrat, pacifico } from './font';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${montserrat.className} ${pacifico.variable}`}>
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
